[2022-07-27 23:18:19,936] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: tutorial-python-op.branch scheduled__2022-02-01T04:10:00+00:00 [queued]>
[2022-07-27 23:18:19,963] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: tutorial-python-op.branch scheduled__2022-02-01T04:10:00+00:00 [queued]>
[2022-07-27 23:18:19,964] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-27 23:18:19,964] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-07-27 23:18:19,965] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-27 23:18:19,994] {taskinstance.py:1377} INFO - Executing <Task(BranchPythonOperator): branch> on 2022-02-01 04:10:00+00:00
[2022-07-27 23:18:20,003] {standard_task_runner.py:52} INFO - Started process 48466 to run task
[2022-07-27 23:18:20,008] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'tutorial-python-op', 'branch', 'scheduled__2022-02-01T04:10:00+00:00', '--job-id', '81', '--raw', '--subdir', 'DAGS_FOLDER/test5.py', '--cfg-path', '/var/folders/6v/f1q42tlx39bf4xb4nltqccj00000gn/T/tmpxvmf7a94', '--error-file', '/var/folders/6v/f1q42tlx39bf4xb4nltqccj00000gn/T/tmp21fnqcrc']
[2022-07-27 23:18:20,010] {standard_task_runner.py:80} INFO - Job 81: Subtask branch
[2022-07-27 23:18:20,117] {task_command.py:369} INFO - Running <TaskInstance: tutorial-python-op.branch scheduled__2022-02-01T04:10:00+00:00 [running]> on host janghuisuui-MacBookAir.local
[2022-07-27 23:18:20,289] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=your-email@g.com
AIRFLOW_CTX_DAG_OWNER=owner-name
AIRFLOW_CTX_DAG_ID=tutorial-python-op
AIRFLOW_CTX_TASK_ID=branch
AIRFLOW_CTX_EXECUTION_DATE=2022-02-01T04:10:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-02-01T04:10:00+00:00
[2022-07-27 23:18:20,290] {python.py:173} INFO - Done. Returned value was: cal_m_id
[2022-07-27 23:18:20,453] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/operators/python.py", line 220, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Branch callable must return valid task_ids. Invalid tasks found: {'cal_m_id'}
[2022-07-27 23:18:20,456] {taskinstance.py:1395} INFO - Marking task as UP_FOR_RETRY. dag_id=tutorial-python-op, task_id=branch, execution_date=20220201T041000, start_date=20220727T141819, end_date=20220727T141820
[2022-07-27 23:18:20,480] {standard_task_runner.py:92} ERROR - Failed to execute job 81 for task branch (Branch callable must return valid task_ids. Invalid tasks found: {'cal_m_id'}; 48466)
[2022-07-27 23:18:20,517] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-27 23:18:20,894] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
