[2022-07-27 23:18:18,361] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: tutorial-python-op.branch scheduled__2022-02-01T00:00:00+00:00 [queued]>
[2022-07-27 23:18:18,388] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: tutorial-python-op.branch scheduled__2022-02-01T00:00:00+00:00 [queued]>
[2022-07-27 23:18:18,388] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-27 23:18:18,389] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-07-27 23:18:18,389] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-27 23:18:18,417] {taskinstance.py:1377} INFO - Executing <Task(BranchPythonOperator): branch> on 2022-02-01 00:00:00+00:00
[2022-07-27 23:18:18,429] {standard_task_runner.py:52} INFO - Started process 48268 to run task
[2022-07-27 23:18:18,435] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'tutorial-python-op', 'branch', 'scheduled__2022-02-01T00:00:00+00:00', '--job-id', '73', '--raw', '--subdir', 'DAGS_FOLDER/test5.py', '--cfg-path', '/var/folders/6v/f1q42tlx39bf4xb4nltqccj00000gn/T/tmphlwirptx', '--error-file', '/var/folders/6v/f1q42tlx39bf4xb4nltqccj00000gn/T/tmp1noljvb_']
[2022-07-27 23:18:18,438] {standard_task_runner.py:80} INFO - Job 73: Subtask branch
[2022-07-27 23:18:18,575] {task_command.py:369} INFO - Running <TaskInstance: tutorial-python-op.branch scheduled__2022-02-01T00:00:00+00:00 [running]> on host janghuisuui-MacBookAir.local
[2022-07-27 23:18:18,737] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=your-email@g.com
AIRFLOW_CTX_DAG_OWNER=owner-name
AIRFLOW_CTX_DAG_ID=tutorial-python-op
AIRFLOW_CTX_TASK_ID=branch
AIRFLOW_CTX_EXECUTION_DATE=2022-02-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-02-01T00:00:00+00:00
[2022-07-27 23:18:18,738] {python.py:173} INFO - Done. Returned value was: call_a_id
[2022-07-27 23:18:18,833] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/operators/python.py", line 220, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Branch callable must return valid task_ids. Invalid tasks found: {'call_a_id'}
[2022-07-27 23:18:18,837] {taskinstance.py:1395} INFO - Marking task as UP_FOR_RETRY. dag_id=tutorial-python-op, task_id=branch, execution_date=20220201T000000, start_date=20220727T141818, end_date=20220727T141818
[2022-07-27 23:18:18,864] {standard_task_runner.py:92} ERROR - Failed to execute job 73 for task branch (Branch callable must return valid task_ids. Invalid tasks found: {'call_a_id'}; 48268)
[2022-07-27 23:18:18,902] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-27 23:18:19,068] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
