[2022-07-24 23:16:04,901] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: my_python_dag.task_1 manual__2022-07-24T14:16:03.665623+00:00 [queued]>
[2022-07-24 23:16:04,908] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: my_python_dag.task_1 manual__2022-07-24T14:16:03.665623+00:00 [queued]>
[2022-07-24 23:16:04,908] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-24 23:16:04,908] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-24 23:16:04,908] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-24 23:16:04,917] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): task_1> on 2022-07-24 14:16:03.665623+00:00
[2022-07-24 23:16:04,923] {standard_task_runner.py:52} INFO - Started process 97239 to run task
[2022-07-24 23:16:04,929] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'my_python_dag', 'task_1', 'manual__2022-07-24T14:16:03.665623+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/test3.py', '--cfg-path', '/var/folders/6v/f1q42tlx39bf4xb4nltqccj00000gn/T/tmp9hkh1bdw', '--error-file', '/var/folders/6v/f1q42tlx39bf4xb4nltqccj00000gn/T/tmpit55qbio']
[2022-07-24 23:16:04,932] {standard_task_runner.py:80} INFO - Job 22: Subtask task_1
[2022-07-24 23:16:04,994] {task_command.py:369} INFO - Running <TaskInstance: my_python_dag.task_1 manual__2022-07-24T14:16:03.665623+00:00 [running]> on host janghuisuui-MacBookAir.local
[2022-07-24 23:16:05,061] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=testJang
AIRFLOW_CTX_DAG_ID=my_python_dag
AIRFLOW_CTX_TASK_ID=task_1
AIRFLOW_CTX_EXECUTION_DATE=2022-07-24T14:16:03.665623+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-24T14:16:03.665623+00:00
[2022-07-24 23:16:05,062] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: print_fruit() missing 1 required positional argument: 'fruit_name'
[2022-07-24 23:16:05,073] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=my_python_dag, task_id=task_1, execution_date=20220724T141603, start_date=20220724T141604, end_date=20220724T141605
[2022-07-24 23:16:05,082] {standard_task_runner.py:92} ERROR - Failed to execute job 22 for task task_1 (print_fruit() missing 1 required positional argument: 'fruit_name'; 97239)
[2022-07-24 23:16:05,112] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-24 23:16:05,147] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
