[2022-07-24 23:11:28,111] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: my_python_dag.task_1 manual__2022-07-24T14:11:27.500902+00:00 [queued]>
[2022-07-24 23:11:28,117] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: my_python_dag.task_1 manual__2022-07-24T14:11:27.500902+00:00 [queued]>
[2022-07-24 23:11:28,117] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-24 23:11:28,117] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-24 23:11:28,117] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-24 23:11:28,124] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): task_1> on 2022-07-24 14:11:27.500902+00:00
[2022-07-24 23:11:28,133] {standard_task_runner.py:52} INFO - Started process 94295 to run task
[2022-07-24 23:11:28,144] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'my_python_dag', 'task_1', 'manual__2022-07-24T14:11:27.500902+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/test3.py', '--cfg-path', '/var/folders/6v/f1q42tlx39bf4xb4nltqccj00000gn/T/tmpnvvqsq41', '--error-file', '/var/folders/6v/f1q42tlx39bf4xb4nltqccj00000gn/T/tmpfd5f5wsd']
[2022-07-24 23:11:28,148] {standard_task_runner.py:80} INFO - Job 15: Subtask task_1
[2022-07-24 23:11:28,207] {task_command.py:369} INFO - Running <TaskInstance: my_python_dag.task_1 manual__2022-07-24T14:11:27.500902+00:00 [running]> on host janghuisuui-MacBookAir.local
[2022-07-24 23:11:28,266] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=testJang
AIRFLOW_CTX_DAG_ID=my_python_dag
AIRFLOW_CTX_TASK_ID=task_1
AIRFLOW_CTX_EXECUTION_DATE=2022-07-24T14:11:27.500902+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-24T14:11:27.500902+00:00
[2022-07-24 23:11:28,267] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: print_ftruit() missing 1 required positional argument: 'fruit_name'
[2022-07-24 23:11:28,275] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=my_python_dag, task_id=task_1, execution_date=20220724T141127, start_date=20220724T141128, end_date=20220724T141128
[2022-07-24 23:11:28,283] {standard_task_runner.py:92} ERROR - Failed to execute job 15 for task task_1 (print_ftruit() missing 1 required positional argument: 'fruit_name'; 94295)
[2022-07-24 23:11:28,320] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-24 23:11:28,353] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
